# MySQL Server
mysql:
  image: mysql:5.7
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: local_drupal
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  expose:
    - "3306"
  restart: always
  volumes:
    - ./data/database:/var/lib/mysql

web:
  build: .
  # Environment variables
  environment:
    # Drupal settings
    DRUPAL_PROFILE: custom
    DRUPAL_SITE_NAME: drupal
    DRUPAL_USER: admin
    DRUPAL_PASS: admin
    DRUPAL_DBURL: mysql://drupal:drupal@mysql:3306/local_drupal
  ports:
    - "80:80"
  volumes:
    - ./data/files:/var/www/html/sites/default/files
    - ./data/settings.php:/var/www/html/sites/default/settings.php
    - ./configuration:/var/www/configuration
  links:
    - mysql:mysql
  working_dir: /var/www/html
  restart: always
